version: '3'
services:
  bank-service:
    env_file:
      - .env
    build:
      context: ../lucky-wheel-game/
      dockerfile: ../lucky-wheel-game/lucky-wheel-game.dockerfile
    #restart: always
    ports:
      - "${APP_HOST_PORT}:${APP_CONTAINER_PORT}"
    expose:
      - ${APP_HOST_PORT}
    deploy:
      mode: replicated
      replicas: 1
    container_name: game-service
    depends_on:
      - redisdb
  redisdb:
    image: redis
    env_file:
      - .env
    ports:
      - "${REDIS_HOST_PORT}:${REDIS_CONTAINER_PORT}"
    expose:
      - "${REDIS_HOST_PORT}"
    container_name: "${REDIS_CONTAINER_NAME}"
    deploy:
      mode: replicated
      replicas: 1
#volumes:
#   mysqldb:
#    driver: local